services:
  opensearch:
    image: opensearchproject/opensearch:2.13.0
    environment:
      - discovery.type=single-node
      - OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "9200:9200"
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200 >/dev/null || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 30

  neo4j:
    image: neo4j:5.20.0
    environment:
      - NEO4J_AUTH=neo4j/test
      - NEO4JLABS_PLUGINS=[]
      - NEO4J_server_config_strict__validation_enabled=false
    ports:
      - "7474:7474"
      - "7687:7687"

  traceit-api:
    build:
      context: ..
      dockerfile: Containerfile.api
    container_name: traceit-api
    env_file:
      - ../.env
    environment:
      - OPENSEARCH_URL=${OPENSEARCH_URL}
      - OS_INDEX=${OS_INDEX}
      - NEO4J_URL=${NEO4J_URL}
      - NEO4J_USER=${NEO4J_USER}
      - NEO4J_PASS=${NEO4J_PASS}
    depends_on:
      - opensearch
      - neo4j
    ports:
      - "8000:8000"
    command: ["uvicorn", "api.strands_app:app", "--host", "0.0.0.0", "--port", "8000"]

  traceit-ui:
    build:
      context: ../ui
      dockerfile: Containerfile.ui
    container_name: traceit-ui
    depends_on:
      - traceit-api
    ports:
      - "4200:4200"
    environment:
      - NODE_OPTIONS=--max_old_space_size=2048
    command: ["npm", "run", "start"]
