FROM node:20-slim
WORKDIR /app
COPY package.json angular.json tsconfig.json tsconfig.app.json proxy.compose.conf.json proxy.local.conf.json /app/
COPY src /app/src
RUN npm ci
EXPOSE 4200
CMD ["npm","run","start"]
